import { expect,test } from './fixtures/test';
import { deflateSync,gzipSync,gunzipSync } from 'node:zlib';
import { readFileSync } from 'node:fs';
import { matchesTeam } from '../../src/pages/competitive/hakuraku-query';
import type { Performer,Requirement } from '../../src/pages/competitive/hakuraku-types';
const cmFixture=JSON.parse(gunzipSync(readFileSync('tests/e2e/fixtures/hakuraku-cm.json.gz')).toString());

const replayCourses=JSON.parse(gunzipSync(readFileSync('tests/e2e/fixtures/replay-courses.json.gz')).toString());

function captureFile(name:string,gzip=false,courseId:number|null=10606) {
  const bytes=Buffer.alloc(127);
  for(const [offset,value] of [[0,4],[4,1],[12,1],[16,12],[20,31],[28,2],[32,16],[72,1],[107,1],[119,0],[123,200001]])bytes.writeInt32LE(value!,offset!);
  for(const [offset,value] of [[8,20],[52,1],[56,14],[76,118.42],[84,.12],[90,1780],[113,.5]])bytes.writeFloatLE(value!,offset!);
  for(const [offset,value] of [[44,5000],[46,1400],[48,1000],[60,5000],[62,1600],[64,900],[111,14]])bytes.writeUInt16LE(value!,offset!);
  bytes[94]=2;bytes[117]=3;bytes[118]=2;
  const json=Buffer.from(JSON.stringify({race_horse_data_array:[{card_id:100101,chara_name:'Uploaded Special Week',speed:1200,skill_array:[200001]}],race_scenario:deflateSync(bytes).toString('base64'),race_course_set:{id:courseId,lane_distance_max:16.875}}));
  return {name,mimeType:gzip?'application/gzip':'application/json',buffer:gzip?gzipSync(json):json};
}

test('race uploads switch between replay and multi-race analysis, retaining valid files',async({page},info)=>{
  for(const [name,json] of Object.entries(replayCourses))await page.route(`**/resources/*/${name}.json*`,route=>route.fulfill({json}));
  await page.route('**/resources/*/room_match_races.json*',route=>route.fulfill({json:{races:[{race_instance_id:800023,course_set_id:10506}]}}));
  await page.goto('/competitive/race-analysis');
  await expect(page.getByRole('heading',{name:'Race Analysis',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Try one demo race',exact:true}).click();
  await page.getByRole('button',{name:'Play',exact:true}).click();
  await expect(page.getByRole('button',{name:'Pause',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Pause',exact:true}).click();
  await page.getByRole('button',{name:/Seek to/}).first().click();
  await expect(page.locator('.event-list button.active')).not.toHaveCount(0);
  await page.getByLabel('Replay time',{exact:true}).evaluate(element=>{(element as HTMLInputElement).value='60';element.dispatchEvent(new Event('input',{bubbles:true}));});
  const playback=page.getByRole('region',{name:'Race playback',exact:true});
  await expect(playback.getByRole('slider',{name:'Replay time',exact:true})).toHaveCount(1);
  await expect(page.locator('.course-progress')).toHaveCount(0);
  const positionsBox=await page.getByLabel('Runner positions by distance and lane',{exact:true}).boundingBox();
  const playbackBox=await playback.boundingBox();
  expect(playbackBox!.y).toBeGreaterThanOrEqual(positionsBox!.y+positionsBox!.height);
  await expect(playback.getByRole('img',{name:/Course elevation/})).toBeVisible();
  const corner=playback.getByRole('button',{name:/Seek to (Final corner|Corner) at/}).first();
  await corner.click();
  await expect(playback.locator('.playback-state')).toContainText('Corner');
  await page.getByLabel('Replay time',{exact:true}).evaluate(element=>{(element as HTMLInputElement).value='60';element.dispatchEvent(new Event('input',{bubbles:true}));});
  await expect(page.locator('.runner-lane')).toHaveCount(0);
  expect(new Set(await page.locator('.replay-marker').evaluateAll(elements=>elements.map(e=>(e as HTMLElement).style.bottom))).size).toBeGreaterThan(1);
  await expect(page.getByRole('complementary',{name:'Race field',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Late race',exact:true}).click();
  await expect(page.locator('.race-phase')).toContainText('Late race');
  const follow=page.locator('.runner-pick').last(),followName=(await follow.getAttribute('aria-label'))!.slice('Follow '.length);
  await follow.click();
  await expect(page.locator('.live-focus')).toContainText(followName);
  await page.getByRole('button',{name:followName+': visible. Change visibility',exact:true}).click();
  await expect(page.getByRole('button',{name:followName+': dimmed. Change visibility',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Show all runners',exact:true}).click();
  const map=page.getByRole('group',{name:'Race course and runner positions',exact:true});
  await expect(map).toBeVisible();
  await expect(map.getByRole('button',{name:'Follow '+followName+' on course',exact:true})).toHaveAttribute('aria-pressed','true');
  const portraitPick=map.locator('.map-runner').last();
  await portraitPick.locator('foreignObject').click();
  await expect(portraitPick).toHaveAttribute('aria-pressed','true');
  const mapPick=map.locator('.map-runner').first(),mapName=(await mapPick.getAttribute('aria-label'))!.slice(7,-10);
  await mapPick.focus();await page.keyboard.press('Enter');
  await expect(page.locator('.live-focus')).toContainText(mapName);
  await expect(page.locator('.replay-marker.selected')).toHaveAttribute('aria-label','Inspect '+mapName);
  await expect(page.getByRole('button',{name:'Follow window',exact:true})).toHaveAttribute('aria-pressed','true');
  await expect(map.locator('.runner-portrait')).toHaveCount(9);
  expect(new Set(await map.locator('.runner-location').evaluateAll(elements=>elements.map(e=>e.getAttribute('data-lane-metres')))).size).toBeGreaterThan(1);
  await expect(map.locator('.runner-trail')).toHaveCount(1);
  const overview=page.getByRole('region',{name:'Course overview',exact:true});
  await expect(overview.getByRole('navigation',{name:'Upcoming course landmarks',exact:true})).toBeVisible();
  const next=overview.locator('.upcoming button').first();
  const nextDistance=Number((await next.getAttribute('aria-label'))!.match(/at ([0-9]+) metres/)![1]);
  await next.click();
  await expect.poll(async()=>Number((await playback.locator('.playback-state').innerText()).match(/Leader ([0-9,]+)/)![1].replaceAll(',',''))).toBeCloseTo(nextDistance,0);
  await expect(map.locator('.map-distance').first()).toBeVisible();
  const transform=()=>map.locator('.track-camera').getAttribute('transform');
  const original=await transform();
  await page.getByRole('button',{name:'Zoom course in',exact:true}).click();
  await expect.poll(transform).not.toBe(original);
  await expect(page.getByRole('button',{name:'Follow window',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'Full course',exact:true}).click();
  await expect(page.getByRole('button',{name:'Follow window',exact:true})).toHaveAttribute('aria-pressed','false');
  await page.getByRole('button',{name:'Follow window',exact:true}).click();
  await expect(page.getByRole('button',{name:'Follow window',exact:true})).toHaveAttribute('aria-pressed','true');
  await expect(page.getByRole('tablist',{name:'Course camera',exact:true})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Compact pack',exact:true})).toHaveCount(0);
  const runnerPosition=()=>map.locator('.map-runner.selected .runner-leader').getAttribute('d');
  const beforeSeek=await runnerPosition();
  await page.getByLabel('Replay time',{exact:true}).evaluate(element=>{(element as HTMLInputElement).value='60';element.dispatchEvent(new Event('input',{bubbles:true}));});
  await expect.poll(runnerPosition).not.toBe(beforeSeek);
  const assertWindowVisible=async()=>{
    const visible=await map.evaluate(async svg=>{
      await new Promise(requestAnimationFrame);
      const box=svg.getBoundingClientRect(),window=svg.querySelector('.pack-range')!.getBoundingClientRect();
      return window.left>=box.left&&window.top>=box.top&&window.right<=box.right&&window.bottom<=box.bottom;
    });
    expect(visible).toBe(true);
  };
  await assertWindowVisible();
  await expect(page.getByRole('complementary',{name:'Race field',exact:true}).locator('.live-focus')).toContainText(mapName);
  for(const value of ['0','90','125']){
    await page.getByLabel('Replay time',{exact:true}).evaluate((element,value)=>{(element as HTMLInputElement).value=value;element.dispatchEvent(new Event('input',{bubbles:true}));},value);
    await assertWindowVisible();
  }
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.getByLabel('Replay time',{exact:true}).evaluate(element=>{(element as HTMLInputElement).value='60';element.dispatchEvent(new Event('input',{bubbles:true}));});
  await assertWindowVisible();
  if(info.project.name==='chromium'){
    await page.getByRole('button',{name:'Fullscreen',exact:true}).click();
    await expect.poll(()=>page.evaluate(()=>document.fullscreenElement?.classList.contains('replay-layout'))).toBe(true);
    await expect(page.getByRole('complementary',{name:'Race field',exact:true}).locator('.live-focus')).toBeVisible();
    await page.getByRole('button',{name:'Exit fullscreen',exact:true}).click();
  }
  await page.getByRole('button',{name:'Display options',exact:true}).click();
  await page.getByRole('checkbox',{name:'Course overview',exact:true}).uncheck();
  await expect(map).toHaveCount(0);
  await page.getByRole('checkbox',{name:'Course overview',exact:true}).check();
  await expect(map).toBeVisible();
  await page.screenshot({path:info.outputPath('race-replay.png'),fullPage:true});
  await page.locator('.upload-section summary').click();
  await page.getByRole('button',{name:'Try 24 demo races',exact:true}).click();
  await expect(page.getByRole('tab',{name:'Combined analysis (24 races)',exact:true})).toBeVisible();
  await page.getByRole('tab',{name:'Skill Analysis',exact:true}).click();
  const skillTable=page.getByRole('table',{name:'Skill Analysis',exact:true});
  await expect(skillTable).toBeVisible();
  await skillTable.getByRole('button',{name:'Activation rate',exact:true}).click();
  const rates=await skillTable.locator('tbody tr[data-virtual-index] td:nth-child(3)').allTextContents();
  expect(rates.map(value=>parseFloat(value))).toEqual(rates.map(value=>parseFloat(value)).sort((a,b)=>b-a));
  await expect(skillTable.getByRole('columnheader',{name:'Activation rate',exact:true})).toHaveAttribute('aria-sort','descending');
  await page.locator('.lazy-surface').first().scrollIntoViewIfNeeded();
  await expect(page.locator('.lazy-surface svg').first()).toBeVisible();
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:info.outputPath('race-analysis.png'),fullPage:true});
  await page.locator('.upload-section summary').click();
  await page.locator('#race-upload').setInputFiles([captureFile('one.json'),captureFile('two.json.gz',true),{name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{}')}]);
  await expect(page.getByRole('tab',{name:'Combined analysis (2 races)',exact:true})).toBeVisible();
  await expect(page.getByText('Some files could not be imported')).toBeVisible();
  await page.getByRole('tab',{name:'Individual replay',exact:true}).click();
  await page.getByRole('button',{name:'Remove race',exact:true}).click();
  await expect(page.getByRole('tab',{name:/Combined analysis/})).toHaveCount(0);
  await expect(page.getByRole('heading',{name:'Race replay',exact:true})).toBeVisible();
  await expect(map).toBeVisible();
  await expect(page.locator('.replay-title')).toContainText('Tokyo · 2,400 m');
  await page.getByRole('button',{name:'Display options',exact:true}).click();
  await page.getByRole('combobox',{name:'Track',exact:true}).click();
  await page.getByRole('option',{name:'Sapporo · 1200m · Turf · Right',exact:true}).click();
  await expect(page.locator('.replay-title')).toContainText('Sapporo · 1,200 m');
  await expect(map).toBeVisible();
  await page.getByRole('combobox',{name:'Track',exact:true}).click();
  await page.getByRole('option',{name:'Auto · Course 10606',exact:true}).click();
  await expect(page.locator('.replay-title')).toContainText('Tokyo · 2,400 m');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
  await page.getByRole('button',{name:'Remove race',exact:true}).click();
  await expect(page.locator('.upload-section')).toHaveAttribute('open','');
  await expect(page.getByRole('button',{name:'Explore a replay →',exact:true})).toBeVisible();
  await page.locator('#race-upload').setInputFiles(captureFile('800023_recorded-race.json',false,null));
  await expect(page.locator('.replay-title')).toContainText('Nakayama · 2,500 m');
  await expect(page.locator('.course-source')).toHaveText('Course detected');
  await expect(map).toBeVisible();
});

test('CM uses Hakuraku charts and captured teams without inventing a replay catalogue',async({page},info)=>{
  const methods:string[]=[];
  let failSkillDetail=true;
  await page.route('https://hakuraku.moe/api/simdata/**',async route=>{
    const request=route.request(),url=new URL(request.url());methods.push(request.method());
    let payload:unknown;
    if(url.pathname.endsWith('/manifest'))payload=cmFixture.manifest;
    else if(url.pathname.endsWith('/summary'))payload=cmFixture.summary;
    else if(url.pathname.includes('/characters/'))payload=cmFixture.context;
    else if(url.pathname.endsWith('/team-distribution'))payload=cmFixture.distribution;
    else if(url.pathname.endsWith('/skills/overview'))payload=cmFixture.skills;
    else if(url.pathname.includes('/skills/details/')){
      if(failSkillDetail){failSkillDetail=false;await route.fulfill({status:503,json:{error:'temporarily unavailable'},headers:{'access-control-allow-origin':'*'}});return;}
      payload={...cmFixture.skillDetail,skillId:Number(url.pathname.split('/').at(-1))};
    }
    else if(url.pathname.endsWith('/teams')){
      const slots=JSON.parse(url.searchParams.get('slots')??'[{}, {}, {}]') as Requirement[];
      const matching=(cmFixture.teams.teams as Performer[]).filter(t=>matchesTeam(t.members,slots));
      payload={...cmFixture.teams,teams:matching,totalTeams:matching.length,totalOwners:matching.length};
    }else if(url.pathname.includes('/teams/')){
      const id=url.pathname.split('/').at(-1),team=(cmFixture.teams.teams as Performer[]).find(t=>t.id===id);
      payload={snapshotId:cmFixture.summary.snapshotId,team,skills:{}};
    }else throw new Error('Unexpected Hakuraku request '+url);
    await route.fulfill({json:payload,headers:{'access-control-allow-origin':'*'}});
  });
  await page.goto('/competitive/cm-data');
  await expect(page.getByRole('tab',{name:'Introduction',exact:true})).toHaveAttribute('aria-selected','true',{timeout:15000});
  await expect(page.getByRole('tab',{name:'Replays',exact:true})).toHaveCount(0);
  await expect(page.getByRole('tab',{name:'Overview',exact:true})).toHaveCount(0);
  await expect(page.locator('.data-footer')).toContainText('Hakuraku published data · 10,000,000 simulated races');
  await page.getByRole('tab',{name:'Strategy Analysis',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Effects of style saturation',exact:true})).toBeVisible();
  const front=cmFixture.summary.styles.find((r:{style:number})=>r.style===1);
  await expect(page.locator('.style-row').filter({hasText:'Front Runner'})).toContainText((front.winShare*100).toFixed(1)+'%');
  await expect(page.getByRole('img',{name:'Per-Uma win rate versus number of the same style',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Expand Effects of style saturation',exact:true}).click();
  await page.getByRole('dialog').getByText('Inspect values',{exact:true}).click();
  await expect(page.getByRole('dialog').getByRole('table')).toContainText('95% interval');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button',{name:'Expand Effects of style saturation',exact:true})).toBeFocused();
  await page.screenshot({path:info.outputPath('cm-strategy.png'),fullPage:true});
  await page.getByRole('tab',{name:'Field',exact:true}).click();
  await expect(page.getByRole('img',{name:'Debuffer win rate versus styles in the field',exact:true})).toBeVisible();
  await page.getByRole('tab',{name:'Uma Analysis',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Individual vs. team win rate',exact:true})).toBeVisible();
  await expect(page.locator('.bubble')).toContainText('Individual win rate');
  await expect(page.locator('.bubble')).toContainText('Team win rate');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:info.outputPath('cm-uma-field.png'),fullPage:true});
  await page.getByRole('searchbox',{name:'Find an Uma',exact:true}).fill('no such uma');
  await expect(page.getByText('No Umas match these chart filters.',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Reset chart filters',exact:true}).click();
  await page.getByRole('searchbox',{name:'Find an Uma',exact:true}).fill('Kitasan Black');
  await page.getByRole('button',{name:'Expand Individual vs. team win rate',exact:true}).click();
  const umaDialog=page.getByRole('dialog');
  await umaDialog.locator('.bubble [role="button"]').first().click();
  await expect(umaDialog.getByRole('region',{name:'Uma chart details',exact:true})).toContainText('Kitasan Black');
  const kitasan=cmFixture.summary.pairs.find((p:{key:string})=>p.key==='106801:1');
  await expect(umaDialog.locator('.inspection')).toContainText((kitasan.individual*100).toFixed(1)+'%');
  await expect(umaDialog.locator('.inspection img')).toHaveAttribute('src',/\/game-assets\/character_thumbs\//);
  await page.screenshot({path:info.outputPath('cm-uma-expanded.png')});
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button',{name:'Expand Individual vs. team win rate',exact:true})).toBeFocused();
  await page.getByRole('tab',{name:'Strategy Analysis',exact:true}).click();
  await expect(page.getByRole('tab',{name:'Field',exact:true})).toHaveAttribute('aria-selected','true');
  await page.getByRole('tab',{name:'Uma Analysis',exact:true}).click();
  await expect(page.getByRole('searchbox',{name:'Find an Uma',exact:true})).toHaveValue('Kitasan Black');
  await page.screenshot({path:info.outputPath('cm-uma.png'),fullPage:true});
  await page.getByRole('tab',{name:'Skill Analysis',exact:true}).click();
  await expect(page.getByRole('table',{name:'CM Skill Analysis',exact:true})).toBeVisible();
  await page.getByRole('searchbox',{name:'Search skills',exact:true}).fill('no such skill');
  await expect(page.getByText('No skills match these filters.',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Reset skill filters',exact:true}).click();
  await page.getByRole('searchbox',{name:'Search skills',exact:true}).fill('10071');
  await page.getByRole('button',{name:'Inspect Skill 10071',exact:true}).click();
  const retry=page.getByRole('button',{name:'Retry activation data',exact:true});
  await expect(retry).toBeVisible();await retry.click();
  await expect(page.locator('.lane svg[role="slider"]')).toHaveCount(1);
  await page.screenshot({path:info.outputPath('cm-skills.png'),fullPage:true});
  await page.getByRole('tab',{name:'Uma Analysis',exact:true}).click();
  await page.getByRole('button',{name:'Find teams',exact:true}).click();
  await expect(page.getByRole('tab',{name:'Archetype Analysis',exact:true})).toHaveAttribute('aria-selected','true');
  await expect(page.locator('.team-row').first()).toContainText('Kitasan Black');
  await page.getByRole('button',{name:'Reset',exact:true}).click();
  await page.locator('.team-row .member').first().click();
  const detail=page.getByRole('dialog');
  await expect(detail.locator('.build')).toHaveCount(3);
  await expect(detail.getByRole('button',{name:/replay/i})).toHaveCount(0);
  await expect(detail.locator('.skill-chip').first()).toBeVisible();
  await detail.getByText('Training setup',{exact:true}).first().click();
  await detail.locator('.parent-builds summary').first().click();
  await expect(detail.locator('.parent-sparks .spark').first()).toBeVisible();
  await page.screenshot({path:info.outputPath('cm-build.png')});
  await detail.getByRole('button',{name:'Add to lobby',exact:true}).click();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('tab',{name:'Archetype Analysis',exact:true})).toHaveAttribute('aria-selected','true');
  for(let i=0;i<2;i++)await page.getByRole('button',{name:'+ Add',exact:true}).first().click();
  await expect(page.getByRole('button',{name:'Full',exact:true}).first()).toBeDisabled();
  await page.getByRole('tab',{name:'Lobby Builder (3/3)',exact:true}).click();
  await expect(page.locator('.team .runner')).toHaveCount(9);
  await expect(page.getByRole('button',{name:'Run race',exact:true})).toBeDisabled();
  await expect(page.getByRole('button',{name:'Export lobby',exact:true})).toHaveCount(0);
  await page.getByLabel('Lobby seed',{exact:true}).fill('2147483648');
  await expect(page.getByRole('alert')).toContainText('32-bit');
  await page.getByLabel('Lobby seed',{exact:true}).fill('42');
  await page.locator('.gate').first().getByRole('combobox').click();
  await page.getByRole('option',{name:'Gate 1',exact:true}).click();
  await page.locator('.gate').nth(1).getByRole('combobox').click();
  await expect(page.getByRole('option',{name:'Gate 1',exact:true})).toBeDisabled();
  await page.keyboard.press('Escape');
  await page.screenshot({path:info.outputPath('cm-lobby.png'),fullPage:true});
  await page.getByRole('tab',{name:'Archetype Analysis',exact:true}).click();
  await page.getByRole('tab',{name:'Lobby Builder (3/3)',exact:true}).click();
  await expect(page.getByLabel('Lobby seed',{exact:true})).toHaveValue('42');
  await expect(page.locator('.gate').first().getByRole('combobox')).toContainText('Gate 1');
  expect(methods.every(method=>method==='GET')).toBe(true);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
});

test('master data executes SQLite, reports errors, inspects schemas and exports results',async({page},info)=>{
  await page.goto('/tools/master-data');
  await expect(page.getByRole('button',{name:'Run query',exact:true})).toBeEnabled({timeout:30000});
  await page.getByLabel('SQL query',{exact:true}).fill('SELECT COUNT(*) AS count FROM chara');
  await page.getByRole('button',{name:'Run query',exact:true}).click();
  await expect(page.getByRole('table',{name:'SQL query results',exact:true})).toContainText('count');
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:'Export JSON',exact:true}).click();
  expect((await download).suggestedFilename()).toBe('master-data.json');
  await page.getByLabel('SQL query',{exact:true}).fill('SELECT * FROM missing_table');
  await page.getByRole('button',{name:'Run query',exact:true}).click();
  await expect(page.getByText('no such table: missing_table',{exact:true})).toBeVisible();
  await page.getByLabel('SQL query',{exact:true}).fill('SELECT * FROM chara LIMIT 10');
  await page.getByRole('button',{name:'Run query',exact:true}).click();
  await expect(page.getByText(/^10 rows ·/)).toBeVisible();
  await page.getByLabel('SQL query',{exact:true}).fill('DELETE FROM chara');
  await page.getByRole('button',{name:'Run query',exact:true}).click();
  await expect(page.getByText('attempt to write a readonly database',{exact:true})).toBeVisible();
  await page.getByLabel('SQL query',{exact:true}).fill('SELECT * FROM chara LIMIT 10');
  await page.getByRole('button',{name:'Run query',exact:true}).click();
  await expect(page.getByRole('table',{name:'SQL query results',exact:true})).toBeVisible();
  await page.screenshot({path:info.outputPath('master-browser.png'),fullPage:true});
  await page.getByRole('tab',{name:'Schema & References',exact:true}).click();
  await page.getByRole('heading',{name:'Columns',exact:true}).waitFor();
  await page.screenshot({path:info.outputPath('master-data.png'),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
});

test('research opens original notes with math, attachments, and mobile layouts in both themes',async({page},info)=>{
  await page.goto('/research');
  await expect(page.locator('.notes .note')).toHaveCount(10);
  await page.screenshot({path:info.outputPath('research-library.png'),fullPage:true});
  await page.getByRole('button',{name:'Race mechanics 3',exact:true}).click();
  await expect(page.locator('.notes .note')).toHaveCount(3);
  await page.getByRole('searchbox',{name:'Search research',exact:true}).fill('spot struggle');
  await page.locator('.notes .note').click();
  await expect(page.locator('.markdown .katex').first()).toBeVisible();
  if(info.project.name==='chromium'){
    await page.getByRole('navigation',{name:'Article outline'}).getByRole('link',{name:'Baseline mechanics',exact:true}).click();
    await expect(page).toHaveURL(/spot-struggle#section-0/);
    await expect(page.getByRole('heading',{name:'Baseline mechanics',exact:true})).toBeVisible();
  }
  for(const image of await page.locator('.markdown img').all()) {
    await image.evaluate(element=>element.scrollIntoView({block:'center'}));
    await expect.poll(()=>image.evaluate(element=>(element as HTMLImageElement).complete&&(element as HTMLImageElement).naturalWidth>0)).toBe(true);
  }
  await page.evaluate(()=>window.scrollTo(0,0));
  for(const theme of ['dark','light']) {
    await page.evaluate(value=>{document.documentElement.dataset.theme=value;},theme);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
    await page.screenshot({path:info.outputPath(`research-${theme}.png`)});
  }
});
