<script lang="ts">
  import {tick} from 'svelte';
  import Artwork from '@/components/Artwork.svelte';
  import Button from '@/components/Button.svelte';
  import SelectField from '@/components/SelectField.svelte';
  import TextField from '@/components/TextField.svelte';
  import {virtualScroll,type VirtualRange} from '@/lib/virtual-scroll';
  import type { Requirement,Summary } from './hakuraku-types';
  import { pct,number,styleNames,styleOrder } from './cm-data';
  import { portrait } from './analysis-view';
  import { fieldRows,percentagePoints } from './cm-exploration';
  let {data,colors,colorblind=false,view='field',selected=$bindable(''),scope=$bindable('all'),onfind}:{
    data:Summary;colors:Record<number,string>;colorblind?:boolean;view:string;selected?:string;scope?:string;
    onfind:(slots:Requirement[])=>void;
  }=$props();
  let search=$state(''),minimum=$state('20'),metric=$state('team'),sort=$state('share'),descending=$state(true),range=$state<VirtualRange>({start:0,end:0});
  let inspector=$state<HTMLElement>(),canvas=$state<HTMLElement>();
  const scopedPairs=$derived(data.pairs.filter(p=>scope==='all'||p.style===Number(scope)));
  const visibleStyles=$derived(scope==='all'?styleOrder:[Number(scope)]);
  const rows=$derived(fieldRows(scopedPairs,Number(minimum),search).sort((a,b)=>{
    if(sort==='name')return a.name.localeCompare(b.name)*(descending?-1:1);
    if(sort==='share')return (a.share-b.share)*(descending?-1:1);
    const av=a.cells.get(Number(sort)),bv=b.cells.get(Number(sort));
    if(!av||!bv)return av?-1:bv?1:0;
    return ((metric==='team'?av.team:av.individual)-(metric==='team'?bv.team:bv.individual))*(descending?-1:1);
  }));
  function order(key:string){descending=sort===key?!descending:key!=='name';sort=key;}
  const ranked=$derived(scopedPairs.filter(p=>p.owners>=Number(minimum)&&(p.name+' '+p.outfit+' '+p.card).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>metric==='team'?b.teamCI[0]-a.teamCI[0]:b.individualCI[0]-a.individualCI[0]));
  const current=$derived(scopedPairs.find(p=>p.key===selected));
  const baseline=$derived(metric==='team'?1/3:1/9);
  const axisMax=$derived(Math.max(baseline*1.25,...ranked.map(p=>(metric==='team'?p.teamCI:p.individualCI)[1]))*1.04);
  const maxPop=$derived(Math.max(.001,...data.pairs.map(p=>p.pop)));
  const positive=$derived(colorblind?'var(--accent-primary)':'var(--accent-secondary)');
  const negative=$derived(colorblind?'var(--accent-purple)':'var(--accent-error)');
  const cellColor=(rate:number,neutral:number)=>'color-mix(in srgb, '+(rate>=neutral?positive:negative)+' '+Math.min(46,8+Math.abs(rate-neutral)*100)+'%, transparent)';
  async function inspect(key:string){selected=key;await tick();if(matchMedia('(max-width:1000px)').matches)inspector?.scrollIntoView({block:'start',behavior:'instant'});}
</script>
<div class="explorer" class:inspecting={!!current} class:scoped={scope!=='all'} style:--map-positive={positive} style:--map-negative={negative}>
  <section class="canvas" bind:this={canvas}>
    
      <header><span class="eyebrow">{view==='field'?'UMA DATA / ROLE MAP':'UMA DATA / PERFORMANCE RANGES'}</span><h2>{view==='field'?'Uma performance by role':'Uma performance ranges'}</h2><p>{view==='field'?'Published results for each outfit and role. Select an entry for its sample size, intervals, and captured builds.':'Ranked by the lower end of the published 95% interval. These intervals describe the simulated sample.'}</p></header>
      <div class="filters"><TextField id="trial-uma-search" type="search" label="Find an Uma" placeholder="Name, outfit, or ID" prefixIcon="search" bind:value={search}/><SelectField id="uma-map-style" label="Running style" bind:value={scope} options={[{value:'all',label:'All styles'},...styleOrder.map(id=>({value:String(id),label:styleNames[id]!}))]}/><SelectField id="trial-metric" label="Show performance" bind:value={metric} options={[{value:'team',label:'Associated team win rate'},{value:'individual',label:'Individual win rate'}]}/><SelectField id="trial-sample" label="Minimum players per role" bind:value={minimum} options={[{value:'20',label:'20 players'},{value:'50',label:'50 players'},{value:'5',label:'5 players'},{value:'1',label:'All published results'}]}/></div>
      {#if view==='field'}
        <div class="map-key"><span><i class="above"></i>Above {pct(baseline)} baseline</span><span><i class="below"></i>Below baseline</span><span>Bar = relative popularity in the field</span></div>
        <div class="table-scroll"><table class="field-map" aria-label="Uma role performance map"><thead><tr><th scope="col" aria-sort={sort==='name'?(descending?'descending':'ascending'):'none'}><button class="sort" onclick={()=>order('name')}>Uma / outfit {sort==='name'?(descending?'↓':'↑'):'↕'}</button></th>{#each visibleStyles as id}<th scope="col" aria-sort={sort===String(id)?(descending?'descending':'ascending'):'none'}><button class="sort" onclick={()=>order(String(id))}><i style:background={colors[id]}></i>{styleNames[id]} {sort===String(id)?(descending?'↓':'↑'):'↕'}</button></th>{/each}</tr></thead><tbody use:virtualScroll={{items:rows,key:r=>r.card,root:'closest',estimate:65,searchText:r=>r.name+' '+r.outfit,onrange:r=>range=r}}>
          {#each rows.slice(range.start,range.end) as row,index (row.card)}<tr data-virtual-index={range.start+index}><th scope="row"><div class="identity"><Artwork src={portrait(row.card)} alt="" size="sm"/><span>{row.name}<small>{row.outfit}</small></span></div></th>{#each visibleStyles as id}{@const pair=row.cells.get(id)}<td>{#if pair}{@const value=metric==='team'?pair.team:pair.individual}<button class:chosen={current?.key===pair.key} aria-pressed={current?.key===pair.key} aria-label={'Inspect '+pair.name+' '+pair.outfit+' '+styleNames[id]} style:background={cellColor(value,baseline)} onclick={()=>void inspect(pair.key)}><strong>{pct(value)}</strong><small>{number(pair.owners)} players</small><i class="share" style:width={pair.pop/maxPop*100+'%'}></i></button>{:else}<span class="absent" title="No result meeting the player threshold">—</span>{/if}</td>{/each}</tr>{/each}
        </tbody></table></div>
        {#if !rows.length}<div class="empty"><h3>No matching Umas</h3><p>Try another name or lower the player threshold.</p><Button variant="secondary" onclick={()=>{search='';minimum='1';}}>Reset field filters</Button></div>{/if}
      {:else}
        <div class="range-axis"><span>Uma · role</span><div><span>0%</span><span>{pct(axisMax/2)}</span><span>{pct(axisMax)}</span></div><span>Win rate</span><span>Players</span></div>
        <div class="rankings-scroll"><div class="rankings" use:virtualScroll={{items:ranked,key:p=>p.key,root:'closest',estimate:65,searchText:p=>p.name+' '+p.outfit+' '+styleNames[p.style],onrange:r=>range=r}}>{#each ranked.slice(range.start,range.end) as pair,index (pair.key)}{@const value=metric==='team'?pair.team:pair.individual}{@const ci=metric==='team'?pair.teamCI:pair.individualCI}
          <button data-virtual-index={range.start+index} class="ranking" class:chosen={current?.key===pair.key} aria-pressed={current?.key===pair.key} aria-label={'Inspect '+pair.name+' '+pair.outfit+' '+styleNames[pair.style]} onclick={()=>void inspect(pair.key)}>
            <span class="identity"><Artwork src={portrait(pair.card)} alt="" size="xs"/><span>{pair.name}<small>{pair.outfit} · {styleNames[pair.style]}</small></span></span><span class="range" role="img" aria-label={pct(ci[0],2)+' to '+pct(ci[1],2)+' 95% interval'}><i class="neutral" style:left={baseline/axisMax*100+'%'}></i><i class="interval" style:left={ci[0]/axisMax*100+'%'} style:width={(ci[1]-ci[0])/axisMax*100+'%'} style:background={colors[pair.style]}></i><i class="dot" style:left={value/axisMax*100+'%'} style:background={colors[pair.style]}></i></span><strong>{pct(value)}</strong><small>{number(pair.owners)}</small>
          </button>{/each}</div></div>
        <p class="caption">Dashed line = {pct(baseline)} neutral rate. Dots show observed rates; whiskers show published intervals. Narrow intervals do not remove player or build selection bias.</p>
        {#if !ranked.length}<div class="empty"><h3>No matching results</h3><Button variant="secondary" onclick={()=>{search='';minimum='1';}}>Reset ranking filters</Button></div>{/if}
      {/if}
  </section>
  {#if current}
    <aside class="inspector" aria-label="Selected Uma insight" bind:this={inspector}><div class="back-to-chart"><Button variant="ghost" size="sm" onclick={()=>canvas?.scrollIntoView({block:'start',behavior:'instant'})}>← Back to the chart</Button></div>
      <span class="eyebrow">SELECTED UMA / ROLE</span><div class="selected-identity"><Artwork src={portrait(current.card)} alt="" size="lg"/><div><h3>{current.name}</h3><p>{current.outfit}</p><span class="role"><i style:background={colors[current.style]}></i>{styleNames[current.style]}</span></div></div>
      <dl class="readout"><div><dt>Associated team win rate</dt><dd>{pct(current.team)}</dd><small>{percentagePoints(current.team-1/3)} from neutral</small></div><div><dt>Individual win rate</dt><dd>{pct(current.individual)}</dd><small>{percentagePoints(current.individual-1/9)} from neutral</small></div></dl>
      <div class="evidence"><span>Published 95% intervals</span><p>Team <strong>{pct(current.teamCI[0],2)}–{pct(current.teamCI[1],2)}</strong></p><p>Individual <strong>{pct(current.individualCI[0],2)}–{pct(current.individualCI[1],2)}</strong></p><p>Distinct players <strong>{number(current.owners)}</strong></p><p>Share of this style <strong>{pct(current.stylePop)}</strong></p><p>Share of the whole field <strong>{pct(current.pop)}</strong></p></div>
      <p class="reading">{current.individual<1/9&&current.team>1/3?'Teams containing this Uma perform above the neutral team rate while the Uma’s own rate is below neutral. Inspect its teammates to understand the result.':current.individual>1/9&&current.team>1/3?'Both the individual and associated team rates sit above their neutral baselines in this sample. Inspect the captured builds behind the result.':'Read the individual and team results together. Role, teammates, and captured builds all affect the observed result.'}</p>
      <Button onclick={()=>onfind([{card:current.card,style:current.style},{},{}])}>Find captured builds →</Button><Button variant="ghost" onclick={()=>{selected='';canvas?.scrollIntoView({block:'start',behavior:'instant'});}}>Close details</Button>
      <p class="caption">Associated team performance is not an isolated measure of this Uma’s contribution.</p>
    </aside>
  {/if}
</div>
<style>
  .explorer{display:grid;grid-template-columns:minmax(0,1fr);gap:32px;align-items:start}.explorer.inspecting{grid-template-columns:minmax(0,1fr) 250px}.explorer.scoped .field-map{min-width:290px}.scoped .field-map th:first-child{width:60%}.canvas{min-width:0;scroll-margin-top:80px}.back-to-chart{display:none}header{margin-bottom:24px}.eyebrow{font-size:9px;letter-spacing:.16em;font-weight:650;color:var(--text-secondary)}h2{font-size:clamp(22px,2vw,29px);font-weight:600;letter-spacing:-.04em;margin:10px 0}h3{font-size:17px;letter-spacing:-.02em;margin:0}p{font-size:12px;line-height:1.7;color:var(--text-secondary);margin:8px 0}header p{max-width:74ch}
  .filters{display:flex;gap:12px;flex-wrap:wrap;align-items:end;margin-bottom:20px}.filters>:global(.field){flex:1;min-width:140px}.filters>:global(.field:first-child){flex:1.4;min-width:180px}
  .map-key{display:flex;gap:14px;flex-wrap:wrap;font-size:10px;color:var(--text-secondary);margin:0 0 16px}.map-key span{display:flex;align-items:center;gap:5px}.map-key i,th .sort i{display:inline-block;width:6px;height:6px;border-radius:50%}.above{background:var(--map-positive)}.below{background:var(--map-negative)}
  .table-scroll,.rankings-scroll{overflow:auto;min-width:0;max-height:650px;scrollbar-gutter:stable}.field-map thead th{position:sticky;top:0;z-index:2;background:var(--bg-primary)}.sort{border:0;background:none;color:inherit;font:inherit;cursor:pointer;min-height:32px;white-space:nowrap}.sort i{display:inline-block;width:6px;height:6px;border-radius:50%;margin-right:5px}.sort:hover,th[aria-sort=ascending],th[aria-sort=descending]{color:var(--accent-primary)}.field-map{border-collapse:separate;border-spacing:4px 5px;width:100%;font-size:11px;min-width:710px}.field-map th{font-weight:500;text-align:left;padding:6px 4px;white-space:nowrap}.field-map thead th{font-size:10px;color:var(--text-secondary);text-align:center}.field-map thead th:first-child{text-align:left}.field-map tbody th{width:190px}.identity{display:flex;align-items:center;gap:9px;min-width:0}.identity>span{min-width:0;line-height:1.5}.identity small{display:block;color:var(--text-secondary);font-size:9px;font-weight:400;max-width:160px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.field-map td{padding:0;text-align:center}.field-map td button{position:relative;display:flex;flex-direction:column;justify-content:center;gap:4px;border:0;min-height:55px;width:100%;color:var(--color-text);cursor:pointer;overflow:hidden}.field-map td strong{font-size:13px;font-weight:600}.field-map td small{font-size:9px;color:var(--text-secondary)}.share{position:absolute;height:2px;background:var(--text-secondary);opacity:.5;bottom:0;left:0}.chosen{outline:2px solid var(--accent-primary);outline-offset:-2px}.absent{color:var(--text-disabled);font-size:12px}.empty{padding:50px 0;text-align:center}
  .inspector{scroll-margin-top:80px;position:sticky;top:80px;padding-top:2px;min-width:0}.selected-identity{display:flex;gap:12px;align-items:center;margin:24px 0}.selected-identity h3{font-size:20px}.selected-identity p{font-size:11px;margin:4px 0}.role{display:flex;align-items:center;gap:6px;font-size:11px}.role i{width:6px;height:6px;border-radius:50%}.readout{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:28px 0}.readout dt{font-size:10px;color:var(--text-secondary)}.readout dd{font-size:30px;letter-spacing:-.05em;margin:8px 0 4px;font-variant-numeric:tabular-nums}.readout small{font-size:9px;color:var(--text-secondary)}.evidence{border-top:1px solid var(--border-subtle);padding-top:18px}.evidence>span{font-size:10px;color:var(--text-secondary)}.evidence p{display:flex;justify-content:space-between;gap:10px;font-size:10px;margin:10px 0}.evidence strong{font-weight:500;color:var(--color-text);font-variant-numeric:tabular-nums}.reading{margin:22px 0;font-size:12px}.inspector>:global(button){width:100%;margin-top:8px}.caption{font-size:10px;line-height:1.7;margin:15px 0;color:var(--text-secondary)}
  .range-axis,.ranking{display:grid;grid-template-columns:minmax(155px,1fr) minmax(100px,1.5fr) 60px 48px;gap:15px;align-items:center}.range-axis{padding:12px 5px;font-size:9px;color:var(--text-secondary);text-align:right}.range-axis>span:first-child{text-align:left}.range-axis>div{display:flex;justify-content:space-between}.ranking{width:100%;padding:14px 5px;border:0;border-bottom:1px solid var(--border-subtle);background:transparent;color:var(--color-text);font:inherit;font-size:12px;cursor:pointer;text-align:left}.ranking:hover{background:var(--surface-2)}.ranking strong,.ranking>small{text-align:right;font-variant-numeric:tabular-nums}.ranking>small{font-size:10px;color:var(--text-secondary)}.range{display:block;position:relative;height:28px}.neutral{position:absolute;top:0;bottom:0;border-left:1px dashed var(--text-muted)}.interval{position:absolute;top:12px;height:4px;min-width:2px;background:var(--accent-primary)}.dot{position:absolute;top:10px;width:8px;height:8px;border-radius:50%;transform:translateX(-50%);background:var(--accent-primary)}
  @media(max-width:1250px){.explorer.inspecting{grid-template-columns:minmax(0,1fr) 230px;gap:26px}.readout{gap:10px}.readout dd{font-size:26px}.range-axis,.ranking{grid-template-columns:minmax(130px,1fr) minmax(75px,1.3fr) 48px 40px;gap:8px}}
  @media(max-width:1000px){.back-to-chart{display:block;grid-column:1/-1;margin-bottom:12px}.explorer.inspecting{grid-template-columns:1fr;gap:32px}.inspector{position:static;display:grid;grid-template-columns:1fr 1fr;gap:0 24px;border-top:1px solid var(--border-subtle);padding-top:24px}.inspector>.eyebrow,.reading,.inspector>.caption{grid-column:1/-1}.selected-identity{margin:16px 0}.readout{margin:20px 0}.evidence{grid-column:1/-1}.evidence p{font-size:12px}.readout dt{font-size:11px}}
  @media(max-width:600px){.filters{gap:12px}.filters>:global(.field){min-width:130px}.filters>:global(.field:first-child){min-width:100%}.range-axis,.ranking{grid-template-columns:minmax(105px,1fr) minmax(65px,.8fr) 45px;gap:8px}.range-axis>span:last-child,.ranking>small{display:none}.ranking .identity :global(.art){display:none}.identity small{max-width:115px}.ranking{font-size:11px}.inspector{gap:0 12px}.selected-identity h3{font-size:17px}.selected-identity :global(.art){width:42px;height:42px}.readout dd{font-size:24px}}
</style>
