<script lang="ts">
  import AppPage from '@/layouts/AppPage.svelte';
  import Button from '@/components/Button.svelte';
  import Icon from '@/components/Icon.svelte';
  import Artwork from '@/components/Artwork.svelte';
  import { onMount } from 'svelte';
  import { cmGet,loadCmSummary,pct,type Manifest } from './cm-data';
  import type { Summary,Snapshot } from './hakuraku-types';

  import { portrait } from './analysis-view';
  let snapshot=$state<Snapshot>(),data=$state<Summary>();
  const sample=$derived([...(data?.pairs??[])].sort((a,b)=>b.pop-a.pop).slice(0,5));
  onMount(()=>{const controller=new AbortController();void cmGet<Manifest>('/manifest',controller.signal).then(async value=>{snapshot=value.snapshots[0];if(snapshot)data=await loadCmSummary(snapshot.snapshotId,controller.signal);}).catch(()=>{});return()=>controller.abort();});
</script>
<svelte:head><title>Competitive · uma.moe</title><meta name="description" content="Hakuraku race analysis, Champions Meeting data, and team building in uma.moe."/></svelte:head>
<AppPage routeId="competitive" title="Competitive" description="From the race replay to your next team. Hakuraku’s analysis tools, at home in uma.moe." width="wide">
  <div class="hub">
    <section class="race-tool"><div class="section-label"><Icon name="race" size={18}/><span>YOUR RACES</span></div><h2>There’s more to a race<br/>than the result.</h2><p>Follow the pack, inspect skill timings, and see where your runners lose ground. Add a whole session to compare strategies and builds.</p><div class="workflow"><div><span>01</span><strong>Upload captures</strong><small>One or multiple .json / .json.gz files</small></div><div><span>02</span><strong>Replay & inspect</strong><small>Positions, speed, HP, and activations</small></div><div><span>03</span><strong>Compare the session</strong><small>Umas, teams, skills, and strategy</small></div></div><Button href="/competitive/race-analysis" icon="upload">Open Race Analysis</Button><span class="local-note"><Icon name="lock" size={12}/> Captures stay in your browser</span></section>
    <section class="cm-tool"><div class="section-label"><Icon name="trophy" size={18}/><span>CHAMPIONS MEETING</span><small>HAKURAKU DATA</small></div><div class="cm-heading"><div><h2>{snapshot?.cmId.toUpperCase()??'Champions Meeting'}</h2><p>{snapshot?.meta.course??'Published CM analysis and team builds'}</p></div><span class="sample-size"><strong>{data?(data.meta.populationRaces/1000000).toFixed(0)+'M':'—'}</strong>simulated races</span></div><div class="table-heading"><span>UMA</span><span>WIN RATE</span></div><div class="field">{#each sample as row,index}<a href="/competitive/cm-data"><span class="rank">{index+1}</span><Artwork src={portrait(row.card)} alt="" size="sm"/><div><strong>{row.name}</strong><small>{row.owners.toLocaleString()} players · {row.outfit}</small></div><span class="rate">{pct(row.individual)}</span></a>{/each}</div><div class="cm-footer"><span>Explore strategies, Umas, captured builds, and lobby building.</span><Button href="/competitive/cm-data" variant="secondary">Explore CM Data →</Button></div></section>
  </div>
  <div class="next-tools"><a href="/research"><Icon name="book" size={22}/><div><h3>Research library</h3><p>The mechanics behind the results. Explore Hakuraku’s notes and experiments.</p></div><span>→</span></a><a href="/tools/master-data"><Icon name="database" size={22}/><div><h3>Master Data</h3><p>Inspect game tables, follow field references, and query the database.</p></div><span>→</span></a></div>
</AppPage>
<style>
.hub{display:grid;grid-template-columns:1fr 1.1fr;gap:64px;padding:24px 0 48px}.race-tool,.cm-tool{min-width:0}.section-label{display:flex;align-items:center;gap:10px;font-size:9px;letter-spacing:.1em;color:var(--accent-primary);font-weight:650}.section-label small{margin-left:auto;font-size:8px;padding:3px 0;color:var(--text-secondary)}.race-tool>h2{font-size:clamp(23px,2.5vw,34px);line-height:1.2;letter-spacing:-.04em;margin:26px 0 16px}.race-tool>p{font-size:13px;line-height:1.8;color:var(--text-secondary);max-width:47ch}.workflow{display:grid;gap:22px;margin:30px 0}.workflow>div{display:grid;grid-template-columns:28px 1fr;gap:5px 12px}.workflow span{grid-row:1/3;font:13px var(--font-mono);color:var(--accent-primary);padding-top:2px}.workflow strong{font-size:13px}.workflow small{font-size:11px;color:var(--text-secondary)}.local-note{display:flex;gap:6px;align-items:center;font-size:10px;color:var(--text-secondary);margin-top:14px}.cm-tool .section-label{color:var(--accent-warning)}.cm-heading{display:flex;align-items:center;justify-content:space-between;gap:14px;margin:25px 0}.cm-heading h2{font-size:26px;letter-spacing:-.04em;margin:0 0 6px}.cm-heading p{font-size:11px;color:var(--text-secondary);margin:0}.sample-size{display:grid;text-align:right;font-size:9px;color:var(--text-secondary);gap:4px}.sample-size strong{font-size:28px;font-weight:500;color:var(--text-primary)}.table-heading{display:flex;justify-content:space-between;font-size:8px;letter-spacing:.1em;color:var(--text-secondary);padding-bottom:10px;border-bottom:1px solid var(--border-primary)}.field a{display:flex;gap:12px;align-items:center;padding:10px 0;border-bottom:1px solid var(--border-subtle);text-decoration:none;color:var(--text-primary)}.field a>div{flex:1}.field strong{font-size:12px}.field small{display:block;font-size:10px;color:var(--text-secondary);margin-top:4px}.rank{font-size:10px;color:var(--text-secondary);width:14px}.rate{font-size:16px;color:var(--accent-primary);font-variant-numeric:tabular-nums}.cm-footer{display:flex;align-items:center;gap:14px;justify-content:space-between;margin-top:20px}.cm-footer>span{font-size:10px;line-height:1.6;color:var(--text-secondary);max-width:24ch}.next-tools{display:grid;grid-template-columns:1fr 1fr;gap:64px;border-top:1px solid var(--border-subtle);padding-top:16px}.next-tools>a{display:flex;gap:18px;align-items:center;padding:20px 0;color:var(--text-secondary);text-decoration:none;background:transparent}.next-tools h3{color:var(--text-primary);font-size:14px;margin:0 0 6px}.next-tools p{font-size:11px;line-height:1.6;margin:0}.next-tools>a>span{margin-left:auto;color:var(--accent-primary)}@media(max-width:850px){.hub,.next-tools{grid-template-columns:1fr}.hub,.next-tools{gap:36px}.race-tool,.cm-tool{padding:0}.race-tool>h2 br{display:none}.workflow{gap:16px}.cm-footer{flex-wrap:wrap}}
</style>

