<script lang="ts">
  import type { Summary,Performer,Build } from './hakuraku-types';
  import { pct,number,buildRunner,styleNames } from './cm-data';
  import { portrait,statKeys } from './analysis-view';
  import SelectField from '@/components/SelectField.svelte';
  import Button from '@/components/Button.svelte';
  import Artwork from '@/components/Artwork.svelte';
  import Dialog from '@/components/Dialog.svelte';
  import RunnerBuild from './RunnerBuild.svelte';
  let {data,teams,draft=$bindable({mood:'5',seed:'',gates:{},edits:{}}),onbrowse,onremove,onclear}:{data:Summary;teams:Performer[];draft?:{mood:string;seed:string;gates:Record<string,string>;edits:Record<string,Build>};onbrowse:()=>void;onremove:(team:Performer)=>void;onclear:()=>void}=$props();
  let editing=$state(''),edit=$state<Build>();
  const runners=$derived(teams.flatMap((team,teamIndex)=>team.members.map((runner,i)=>({key:team.id+':'+i,teamIndex,runner:draft.edits[team.id+':'+i]??runner as Build}))));
  const assigned=$derived(new Set(Object.values(draft.gates).filter(Boolean)));
  const invalidSeed=$derived(draft.seed!==''&&(!/^-?\d+$/.test(draft.seed)||Number(draft.seed)<-2147483648||Number(draft.seed)>2147483647));
  function editRunner(key:string,runner:Build){editing=key;edit=structuredClone($state.snapshot(runner));}
</script>
<section class="panel"><div class="heading"><h2>Teams · {teams.length}/3</h2><div class="controls"><SelectField id="lobby-mood" label="Mood" bind:value={draft.mood} options={[{value:'random',label:'Random'},{value:'random-no-awful',label:'Random (no Awful)'},...['Awful','Bad','Normal','Good','Great'].map((label,i)=>({value:String(i+1),label}))]}/><label>Seed<input aria-label="Lobby seed" type="number" min="-2147483648" max="2147483647" placeholder="Random" value={draft.seed} oninput={event=>draft.seed=event.currentTarget.value}/></label><Button variant="secondary" size="sm" onclick={onbrowse}>Browse teams</Button>{#if Object.keys(draft.edits).length}<Button size="sm" variant="ghost" onclick={()=>draft.edits={}}>Reset edits</Button>{/if}{#if teams.length}<Button size="sm" variant="ghost" onclick={onclear}>Clear</Button>{/if}</div></div>
  <div class="teams">{#each [0,1,2] as slot}{@const team=teams[slot]}{#if team}<article class="team" style:--team-color={['#69b7ee','#d194df','#e8ad63'][slot]}><header><h3>Team {slot+1}</h3><Button size="sm" variant="ghost" onclick={()=>onremove(team)}>Remove</Button></header><strong class="rate">{pct(team.wins/team.n)}</strong><p>{number(team.wins)} wins in {number(team.n)} races</p>
    {#each team.members as member,i}{@const key=team.id+':'+i}{@const runner=draft.edits[key]??member as Build}<button class="runner" onclick={()=>editRunner(key,runner)}><Artwork src={portrait(runner.card)} alt="" size="xs"/><span>{data.cards[runner.card]?.name}<small>{styleNames[runner.style===6?6:runner.racingStyle]}{draft.edits[key]?' · Modified':''}</small></span><span class="edit">Edit</span></button>{/each}</article>
  {:else}<button class="empty" onclick={onbrowse}><strong>Team {slot+1}</strong><span>+ Select a team</span></button>{/if}{/each}</div>
</section>
<section class="panel"><h2>Gate assignments · {assigned.size}/9 fixed</h2>{#if runners.length}<div class="gates">{#each teams as team,teamIndex}<div>{#each runners.filter(r=>r.teamIndex===teamIndex) as item}<div class="gate"><Artwork src={portrait(item.runner.card)} alt="" size="xs"/><span><small>Team {teamIndex+1}</small>{data.cards[item.runner.card]?.name}</span><SelectField id={'gate-'+item.key} label={data.cards[item.runner.card]?.name+' gate'} hideLabel value={draft.gates[item.key]??''} onchange={value=>draft.gates={...draft.gates,[item.key]:value}} options={[{value:'',label:'Random gate'},...Array.from({length:9},(_,i)=>({value:String(i+1),label:'Gate '+(i+1),disabled:assigned.has(String(i+1))&&draft.gates[item.key]!==String(i+1)}))]}/></div>{/each}</div>{/each}</div>{:else}<p>Select teams from Archetype Analysis to configure their gates.</p>{/if}</section>
<div class="run"><div><strong>{teams.length===3?'Lobby ready':(3-teams.length)+' more team'+(teams.length===2?'':'s')+' needed'}</strong><p>Simulation is not connected. A replay is created after a lobby race is simulated.</p></div><Button disabled>Run race</Button><Button variant="secondary" disabled>Run 100 races</Button></div>
{#if invalidSeed}<p role="alert">Seed must be a whole 32-bit number.</p>{/if}
<Dialog open={!!editing} title="Edit runner" maxWidth="650px" onclose={()=>editing=''}>
  {#if edit}<RunnerBuild runner={buildRunner(edit,data)}/><div class="stats">{#each statKeys as key,index}<label>{key}<input type="number" min="1" max="2000" bind:value={edit.stats[index]}/></label>{/each}</div><div class="aptitudes">{#each ['Distance','Surface','Style'] as label,index}<SelectField id={'edit-aptitude-'+index} {label} bind:value={edit.aptitudes[index]} options={'SABCDEFG'.split('').map(value=>({value,label:value}))}/>{/each}</div><SelectField id="edit-style" label="Running style" value={String(edit.racingStyle)} onchange={value=>edit!.racingStyle=Number(value)} options={[1,2,3,4].map(value=>({value:String(value),label:styleNames[value]!}))}/><p>Edits apply to this lobby only. The published team and its win rate remain the original snapshot.</p>{/if}
  {#snippet actions()}<Button variant="secondary" onclick={()=>editing=''}>Cancel</Button><Button disabled={!edit||edit.stats.some(n=>!Number.isInteger(n)||n<1||n>2000)} onclick={()=>{if(edit)draft.edits={...draft.edits,[editing]:edit};editing='';}}>Save changes</Button>{/snippet}
</Dialog>
<style>.panel{margin-bottom:40px}.heading,.controls,.run{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.heading{justify-content:space-between;margin-bottom:18px}h2{font-size:17px;font-weight:650;letter-spacing:-.02em;margin:0}h3{font-size:12px;margin:0}.teams,.gates{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.team{min-width:0;padding:20px;background:var(--surface-1);border-radius:var(--radius-lg)}.team h3{color:var(--team-color)}.team header{display:flex;align-items:center;justify-content:space-between}.rate{font-size:36px;font-weight:500;letter-spacing:-.04em;color:var(--team-color)}p{font-size:11px;color:var(--text-secondary);line-height:1.7}.runner{display:flex;gap:10px;align-items:center;width:100%;padding:12px 0;border:0;border-bottom:1px solid var(--border-subtle);background:transparent;color:var(--color-text);font:inherit;font-size:11px;text-align:left;cursor:pointer}.runner>span:nth-child(2){flex:1}.runner:hover{background:var(--surface-2)}small{display:block;color:var(--text-secondary);font-size:9px;margin:4px 0}.edit{color:var(--accent-primary);font-size:10px}.empty{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:200px;gap:10px;padding:20px;border:0;border-radius:var(--radius-lg);background:var(--surface-1);color:var(--text-secondary);font:inherit;cursor:pointer;font-size:12px}.empty:hover{background:var(--surface-2)}.empty strong{color:var(--color-text);font-size:15px;font-weight:550}.empty span{color:var(--accent-primary)}label{font-size:11px;text-transform:capitalize;color:var(--text-secondary)}input{display:block;background:var(--surface-1);border:1px solid var(--border-primary);border-radius:var(--radius-md);color:var(--color-text);font:inherit;padding:9px;width:105px;margin-top:6px;box-sizing:border-box}.gates{margin-top:14px}.gate{display:flex;gap:8px;align-items:center;padding:10px 0;min-width:0;font-size:11px}.gate>span{flex:1;min-width:0}.gate>:global(.field){width:118px}.run{background:var(--cm-tint);padding:20px;border-top:1px solid var(--border-subtle)}.run>div{flex:1}.run strong{font-size:13px}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:20px 0}.stats input{width:100%}.aptitudes{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:16px}@media(max-width:1000px){.teams,.gates{grid-template-columns:1fr}.empty{min-height:130px}.stats{grid-template-columns:repeat(3,1fr)}}</style>


