import './services/sentry-start';
// Language polyfills are generated by Vite for the supported browser targets.
import '@oddbird/popover-polyfill';
import { mount } from 'svelte';
import App from './App.svelte';
import { initializeTheme } from './stores/theme';
import { initializeWorkspace } from './lib/workspaces/workspace-state';
import { initializeAuth } from './services/auth/auth-state';
import './styles/global.css';

document.documentElement.dataset.appPhase = 'mounting';
initializeTheme();
initializeWorkspace();
// The callback owns session verification; an old stored session must not race it.
if (location.pathname !== '/signin' || !new URLSearchParams(location.search).get('token')) void initializeAuth();

const target = document.getElementById('app');
if (!target) throw new Error('The application mount point is missing.');

mount(App, { target });
document.documentElement.dataset.appPhase = 'mounted';
document.getElementById('seo-content')?.remove();
